{
    "name": "APN - Pilates Company",
    "summary": "",
    "description": """
    """,
    "author": "IdooGroup",
    "website": "https://www.idoogroup.com",
    "license": "LGPL-3",
    "category": "",
    "version": "18.0.0.0.1",
    "depends": [
        "base",
        "web",
        "base_geolocalize",
        "apn_group",
    ],
    "data": [
        "data/data_branch_schedule.xml",
        "security/ir.model.access.csv",
        "views/res_users_views.xml",
        "views/company_views.xml",
        "views/branch_views.xml",
        "views/branch_schedule_views.xml",
        "views/branch_room_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {},
    "installable": True,
    "auto_install": False,
    "application": True,
    "sequence": 1,
}